

# CONFIG

CONFIG_FILE: str = 'COFFEE_TORTOISE_TERMINAL_CONFIG.txt'
PARAM_SEP: str = '='
COLLECTION_SEP: str = ','


# CODING

ENCODE: str = 'UTF-8'


# ERROR

EXIT_ERR_STR: str = 'AN ERROR HAS OCCURRED'
EXIT_STR: str = 'NO ERRORS'
PATH_NOT_FOUND: str = 'PATH NOT FOUND'

EXIT_ERR: int = -1
EXIT_SUCCESS: int = 0

ERROR_LST: list[int] = [EXIT_ERR, EXIT_ERR]


# Marks

TEMP_IMAGE: str = 'COFFEE_TORTOISE_TERMINAL_TEMP_IMAGE'